ERROR = "‼"  # Error
WAIT = "⏳"  # Wait
FINISH = "🏁"  # Finished
NOTIFY = "🔔"  # Notify
CANCEL = "❌"  # Cancel
TOP = "👍"  # Top, Yes
DOWN = "👎"  # No
DONE = "✔"  # Done
FAILED = "✖"  # Failed
GOODBYE = "👋"  # Goodbye
QUESTION = "❓"  # Question
KEY = "🔑"  # API Keys
MONEY = "💰"  # Trade
DIAMOND = "💎"  # Balance
LIST = "📒"  # Orders
FLASH = "⚡"  # Ticker
HANDSHAKE = "🤝"  # Trades
CHART = "📊"  # Chart
STARS = "✨"  # Stats
COG = "⚙"  # Settings
ROBOT = "🤖"  # Bot
LINK = "🔗"  # Pair
BACK = "↩"  # Back - alternative 🔙
NEXT = "🔄"  # Trades
BUY = "🔵"  # Buy
SELL = "🔴"  # Sell
SPEECH = "💬"  # Feedback
INFO = "ℹ"  # Info / Help
CHECK = "✅"  # Done
BULLETPOINT = "🔹"  # Bulletpoint
OH_NO = "☹"  # No data
