import tradeogrebot.emoji as emo

BTN_HELP = f"{emo.INFO} Help & Info"
BTN_SHUTDOWN = f"{emo.FINISH} Shutdown"
BTN_REMOVE_AC = f"{emo.CANCEL} Remove Account"
BTN_FEEDBACK = f"{emo.SPEECH} Feedback"
BTN_TRADE = f"{emo.MONEY} Trade"
BTN_BALANCE = f"{emo.DIAMOND} Balance"
BTN_ORDERS = f"{emo.LIST} Orders"
BTN_TICKER = f"{emo.FLASH} Ticker"
BTN_TRADES = f"{emo.HANDSHAKE} Trades"
BTN_CHART = f"{emo.CHART} Chart"
BTN_STATS = f"{emo.STARS} Stats"
BTN_SETTINGS = f"{emo.COG} Settings"
BTN_BOT = f"{emo.ROBOT} Bot"
BTN_PAIR = f"{emo.LINK} Pair"
BTN_API_KEYS = f"{emo.KEY} API Keys"
BTN_BACK = f"{emo.BACK} Back"
BTN_NEXT = f"{emo.NEXT} Next"
BTN_BUY = f"{emo.BUY} Buy"
BTN_SELL = f"{emo.SELL} Sell"
BTN_25 = "25%"
BTN_50 = "50%"
BTN_75 = "75%"
BTN_100 = "100%"
BTN_YES = "Yes"
BTN_NO = "No"
